version: '3.9'

services:

  inventario:
    build: ./inventario
    ports:
      - "50051:50051"
      - "8001:8001"

  pedidos:
    build: ./pedidos
    ports:
      - "8000:8000"
    depends_on:
      - inventario
      - rabbitmq

  notificaciones:
    build: ./notificaciones
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - inventario