# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventario.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10inventario.proto\x12\ninventario\"5\n\x0cStockRequest\x12\x13\n\x0bproducto_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\"1\n\rStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2Y\n\x11InventarioService\x12\x44\n\rReservarStock\x12\x18.inventario.StockRequest\x1a\x19.inventario.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=32
  _globals['_STOCKREQUEST']._serialized_end=85
  _globals['_STOCKRESPONSE']._serialized_start=87
  _globals['_STOCKRESPONSE']._serialized_end=136
  _globals['_INVENTARIOSERVICE']._serialized_start=138
  _globals['_INVENTARIOSERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
