name: CI/CD Pipeline

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Start Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait services
        run: |
          sleep 15

      - name: Install dependencies
        run: |
          pip install pytest requests

      - name: Run tests
        run: |
          pytest -v

      - name: Stop Docker Compose
        if: always()
        run: |
          docker compose down